# Port to be used for the api
ServerPort: 3000
# Database setup
database:
  host: 'localhost'
  port: 5500
  dbname: 'oglike_db'
  user: 'og_administrator'
  password: 'Ww76hQWbbt7zi2ItM6cNo4YYT'
# Logger setup
Logger:
  Name: "oglike"
  Environment: "local"
  Level: "debug"
